# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 81b7636832fde67db70b69f97368d6aba0e79ea6374d816bf814ada29685dd30cfda9bb83ca7d97a24e8323c560493244aeaf109fc05992f19772390e50c59eb

test:
  secret_key_base: f5b587648291cc2fb38494a5faa39b9d2794eeae1ec3527126302d0addfe75b86cf64a7e41a8512a81b3b3d164c5d395d2c75efd720502e77bf12ff04378bfd3

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
